import { PRESS_TYPE_LABELS, type PressArticleType } from '~~/shared/constants/pressTypes'

export type SummaryLocale = 'es' | 'en' | 'ca' | 'eu' | 'gl'

const summaryLabelsEs = {
  aboutBannerTitle: 'Banner “Qué es CREUP”',
  aboutNoBanner: 'Sin banner configurado',
  aboutVisible: 'Visible en la web pública',
  aboutSavedHidden: 'Guardado, pero oculto',
  carouselUntitled: 'Slide sin título',
  statusActive: 'Activo',
  statusInactive: 'Inactivo',
  equalityFallback: 'Documento de igualdad',
  equalityActive: 'Documento activo',
  equalityInactive: 'Documento inactivo',
  newsletterPrefix: 'Newsletter',
  newsletterSendingNow: 'Enviándose ahora',
  newsletterSent: 'Ya enviada',
  newsletterPending: 'Pendiente de envío',
  newsletterVisibleWeb: 'visible en web',
  newsletterHiddenWeb: 'oculta en web',
  pressFallback: 'Artículo de prensa',
  pressTypeFallback: 'Prensa',
  pressDossierTitle: 'Dossier de prensa',
  pressDossierNoPdf: 'Sin PDF configurado',
  pressDossierActive: 'PDF activo',
  pressDossierInactive: 'PDF guardado pero inactivo',
  linksFallback: 'Enlace destacado',
  linksActive: 'Bloque activo',
  linksInactive: 'Bloque inactivo',
  tagPrefix: 'Etiqueta',
  financialFallback: 'Informe económico',
  financialActive: 'Informe activo',
  financialInactive: 'Informe inactivo',
}

type SummaryLabelKey = keyof typeof summaryLabelsEs

export const SUMMARY_LABELS: Record<SummaryLocale, Record<string, string>> = {
  es: summaryLabelsEs,
  en: {
    aboutBannerTitle: '“What is CREUP” banner',
    aboutNoBanner: 'No banner configured',
    aboutVisible: 'Visible on the public website',
    aboutSavedHidden: 'Saved, but hidden',
    carouselUntitled: 'Untitled slide',
    statusActive: 'Active',
    statusInactive: 'Inactive',
    equalityFallback: 'Equality document',
    equalityActive: 'Active document',
    equalityInactive: 'Inactive document',
    newsletterPrefix: 'Newsletter',
    newsletterSendingNow: 'Sending now',
    newsletterSent: 'Already sent',
    newsletterPending: 'Pending delivery',
    newsletterVisibleWeb: 'visible on web',
    newsletterHiddenWeb: 'hidden on web',
    pressFallback: 'Press article',
    pressTypeFallback: 'Press',
    pressDossierTitle: 'Press dossier',
    pressDossierNoPdf: 'No PDF configured',
    pressDossierActive: 'Active PDF',
    pressDossierInactive: 'PDF saved but inactive',
    linksFallback: 'Featured link',
    linksActive: 'Active block',
    linksInactive: 'Inactive block',
    tagPrefix: 'Tag',
    financialFallback: 'Economic report',
    financialActive: 'Active report',
    financialInactive: 'Inactive report',
  } satisfies Record<SummaryLabelKey, string>,
  ca: {
    aboutBannerTitle: 'Bàner “Què és CREUP”',
    aboutNoBanner: 'Sense bàner configurat',
    aboutVisible: 'Visible al web públic',
    aboutSavedHidden: 'Desat, però ocult',
    carouselUntitled: 'Diapositiva sense títol',
    statusActive: 'Actiu',
    statusInactive: 'Inactiu',
    equalityFallback: "Document d'igualtat",
    equalityActive: 'Document actiu',
    equalityInactive: 'Document inactiu',
    newsletterPrefix: 'Newsletter',
    newsletterSendingNow: "S'està enviant ara",
    newsletterSent: 'Ja enviat',
    newsletterPending: "Pendent d'enviament",
    newsletterVisibleWeb: 'visible al web',
    newsletterHiddenWeb: 'ocult al web',
    pressFallback: 'Article de premsa',
    pressTypeFallback: 'Premsa',
    pressDossierTitle: 'Dossier de premsa',
    pressDossierNoPdf: 'Sense PDF configurat',
    pressDossierActive: 'PDF actiu',
    pressDossierInactive: 'PDF desat però inactiu',
    linksFallback: 'Enllaç destacat',
    linksActive: 'Bloc actiu',
    linksInactive: 'Bloc inactiu',
    tagPrefix: 'Etiqueta',
    financialFallback: 'Informe econòmic',
    financialActive: 'Informe actiu',
    financialInactive: 'Informe inactiu',
  } satisfies Record<SummaryLabelKey, string>,
  eu: {
    aboutBannerTitle: '“Zer da CREUP” banner-a',
    aboutNoBanner: 'Banner-ik konfiguratu gabe',
    aboutVisible: 'Web publikoan ikusgai',
    aboutSavedHidden: 'Gordeta, baina ezkutatuta',
    carouselUntitled: 'Izenbururik gabeko diapositiba',
    statusActive: 'Aktibo',
    statusInactive: 'Inaktibo',
    equalityFallback: 'Berdintasun-dokumentua',
    equalityActive: 'Dokumentu aktiboa',
    equalityInactive: 'Dokumentu inaktiboa',
    newsletterPrefix: 'Newsletter',
    newsletterSendingNow: 'Orain bidaltzen',
    newsletterSent: 'Dagoeneko bidalita',
    newsletterPending: 'Bidaltzeke',
    newsletterVisibleWeb: 'webean ikusgai',
    newsletterHiddenWeb: 'webean ezkutatuta',
    pressFallback: 'Prentsa-artikulua',
    pressTypeFallback: 'Prentsa',
    pressDossierTitle: 'Prentsa-dosierra',
    pressDossierNoPdf: 'PDFrik konfiguratu gabe',
    pressDossierActive: 'PDF aktiboa',
    pressDossierInactive: 'PDFa gordeta baina inaktibo',
    linksFallback: 'Esteka nabarmendua',
    linksActive: 'Bloke aktiboa',
    linksInactive: 'Bloke inaktiboa',
    tagPrefix: 'Etiketa',
    financialFallback: 'Txosten ekonomikoa',
    financialActive: 'Txosten aktiboa',
    financialInactive: 'Txosten inaktiboa',
  } satisfies Record<SummaryLabelKey, string>,
  gl: {
    aboutBannerTitle: 'Banner “Que é CREUP”',
    aboutNoBanner: 'Sen banner configurado',
    aboutVisible: 'Visible na web pública',
    aboutSavedHidden: 'Gardado, pero oculto',
    carouselUntitled: 'Diapositiva sen título',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    equalityFallback: 'Documento de igualdade',
    equalityActive: 'Documento activo',
    equalityInactive: 'Documento inactivo',
    newsletterPrefix: 'Newsletter',
    newsletterSendingNow: 'Enviándose agora',
    newsletterSent: 'Xa enviada',
    newsletterPending: 'Pendente de envío',
    newsletterVisibleWeb: 'visible na web',
    newsletterHiddenWeb: 'oculta na web',
    pressFallback: 'Artigo de prensa',
    pressTypeFallback: 'Prensa',
    pressDossierTitle: 'Dossier de prensa',
    pressDossierNoPdf: 'Sen PDF configurado',
    pressDossierActive: 'PDF activo',
    pressDossierInactive: 'PDF gardado pero inactivo',
    linksFallback: 'Ligazón destacada',
    linksActive: 'Bloque activo',
    linksInactive: 'Bloque inactivo',
    tagPrefix: 'Etiqueta',
    financialFallback: 'Informe económico',
    financialActive: 'Informe activo',
    financialInactive: 'Informe inactivo',
  } satisfies Record<SummaryLabelKey, string>,
}

export const resolveSummaryLocale = (locale: string): SummaryLocale =>
  locale === 'en' || locale === 'ca' || locale === 'eu' || locale === 'gl' ? locale : 'es'

// Localized press-type labels for the activity feed (PRESS_TYPE_LABELS itself is es-only).
// es reuses that constant; en/ca/eu/gl mirror the i18n locale conventions.
export const PRESS_TYPE_LABELS_BY_LOCALE: Record<
  SummaryLocale,
  Record<PressArticleType, string>
> = {
  es: PRESS_TYPE_LABELS,
  en: {
    press_release: 'Press release',
    statement: 'Statement',
    media_appearance: 'Media appearance',
  },
  ca: {
    press_release: 'Nota de premsa',
    statement: 'Comunicat',
    media_appearance: 'Aparició als mitjans',
  },
  eu: {
    press_release: 'Prentsa-oharra',
    statement: 'Adierazpena',
    media_appearance: 'Hedabideetako agerpena',
  },
  gl: {
    press_release: 'Nota de prensa',
    statement: 'Comunicado',
    media_appearance: 'Aparición nos medios',
  },
}
