overrides:
  '@internationalized/date': 3.12.2
  ioredis: 5.11.0
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  msgpackr-extract: false
  sharp: true
  unrs-resolver: true
  vue-demi: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
