export const ADMIN_ROUTES = {
  dashboard: '/admin',
  access: '/admin/accesos',
  stats: '/admin/estado',
  carousel: '/admin/carrusel',
  about: '/admin/que-es',
  equality: '/admin/igualdad',
  newsletter: '/admin/newsletter',
  newsletterSubscribers: '/admin/newsletter/suscriptores',
  press: '/admin/prensa',
  pressCreate: '/admin/prensa/crear',
  pressDossier: '/admin/dossier-prensa',
  siteDefaultImages: '/admin/imagenes-por-defecto',
  links: '/admin/enlaces',
  tags: '/admin/etiquetas',
  media: '/admin/medios',
  financialReports: '/admin/informes-economicos',
  login: '/admin/login',
} as const
