/**
 * Legacy members logo proxy endpoint.
 * Kept for compatibility with existing URLs generated by members/sectoriales endpoints.
 */

import { defineEventHandler } from 'h3'
import { proxyExternalAsset } from '../../utils/externalAssetProxy'

export default defineEventHandler((event) => proxyExternalAsset(event, 'image'))
